name: apptex_chat
description: A new Flutter package project.
version: 1.0.0
homepage:

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  #Dependencies
  get: ^4.6.1
  cloud_firestore: ^3.1.15
  firebase_core: ^1.17.0
  firebase_storage: ^10.2.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
 
flutter: